openapi: 3.1.0
info:
  version: 0.0.0.0.1
  title: Dark Alley Admin
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://raw.githubusercontent.com/auniverseaway/da-admin/main/docs/openapi/img/da-logo.png
  description: |
    Dark Alley Admin is used to manage Dark Alley content repositories.

servers:
  - url: https://admin.da.live
paths:
  /source/{owner}/{path}:
    $ref: "./source-api.yaml#/source"
  /list/{owner}/{path}:
    $ref: "./list-api.yaml#/list"

