ownerParam:
  name: owner
  in: path
  description: Repository owner.
  required: true
  schema:
    type: string
repoParam:
  name: repo
  in: path
  description: Name of the repository.
  required: true
  schema:
    type: string
refParam:
  name: ref
  in: path
  description: Ref (branch) of repository.
  required: true
  schema:
    type: string
projectParam:
  name: project
  in: path
  description: Name of project.
  required: true
  schema:
    type: string
siteParam:
  name: site
  in: path
  description: Name of site.
  required: true
  schema:
    type: string