ownerParam:
  name: owner
  in: path
  description: Repository owner.
  required: true
  schema:
    type: string
repoParam:
  name: repo
  in: path
  description: Name of the repository
  required: true
  schema:
    type: string
refParam:
  name: ref
  in: path
  description: Ref (branch) of repository.
  required: true
  schema:
    type: string
topicParam:
  name: topic
  in: path
  description: Topic of a job
  required: true
  schema:
    type: string
jobNameParam:
  name: jobName
  in: path
  description: Name of a job
  required: true
  schema:
    type: string
pathParam:
  name: path
  in: path
  description: Relative path of the resource
  required: true
  schema:
    type: string
editUrlParam:
  name: editUrl
  in: query
  description: URL of the edit (authoring) document
  required: true
  schema:
    type: string
    format: url
statusEditUrlParam:
  name: editUrl
  in: query
  description: Optional URL of the edit (authoring) document
  required: false
  schema:
    oneOf:
      - type: string
        format: url
      - type: string
        enum: ["auto"]
branchParam:
  name: branch
  in: query
  description: Optional branch specifier in case the branch name contains slashes or uppercase characters.
  required: false
  schema:
    oneOf:
      - type: string
        format: url
      - type: string
        enum: ["auto"]

forceUpdateRedirectsParam:
  name: forceUpdateRedirects
  in: query
  description: forces an update of the redirects (only applies when updating/publishing redirects.json)
  required: false
  schema:
    type: boolean

word2mdVersionParam:
  name: hlx-word2md-version
  in: query
  description: selects the version to use when invoking the word2md service.
  required: false
  schema:
    type: string

gdocs2mdVersionParam:
  name: hlx-gdocs2md-version
  in: query
  description: selects the version to use when invoking the gdocs2md service.
  required: false
  schema:
    type: string

html2mdVersionParam:
  name: hlx-html2md-version
  in: query
  description: selects the version to use when invoking the html2md service.
  required: false
  schema:
    type: string

convertIdParam:
  name: id
  in: path
  description: conversion job Id
  required: true
  schema:
    type: string

convertUrlParam:
  name: url
  in: query
  description: URL of video to convert
  required: true
  schema:
    type: string
snIdParam:
  name: snapshotId
  in: path
  description: Id of the snapshot
  required: true
  schema:
    type: string
snFilterParam:
  name: filter
  in: query
  description: >
    Filters the resources that are selected for snapshot. If set to `modified` only the resources
    that have a preview date newer than the live date are selected.
  schema:
    enum: ["all", "modified"]
    default: "all"
snPublishParam:
  name: publish
  in: query
  description: >
    Indicates that the snapshot should be published.
  schema:
    enum: ["true"]
snLockedParam:
  name: locked
  in: query
  description: >
    Locks or unlocks the snapshot.
  schema:
    enum: ["true", "false"]

fromParam:
  name: from
  in: query
  description: >
    Indicates the starting date to get logs from. If not specified, uses the current date minus 15 minutes.
  required: false
  schema:
    type: string
toParam:
  name: to
  in: query
  description: >
    Indicates the ending date to get logs from. If not specified, uses the current date.
  required: false
  schema:
    type: string
nextTokenParam:
  name: nextToken
  in: query
  description: >
    Token returned from a previous call to continue
  required: false
  schema:
    type: string
disableNotificationsParam:
  name: disableNotifications
  in: query
  description: disables notifications for affected resources
  schema:
    type: boolean
