ownerParam:
  name: owner
  in: path
  description: Repository owner.
  required: true
  schema:
    type: string
repoParam:
  name: repo
  in: path
  description: Name of the repository.
  required: true
  schema:
    type: string
refParam:
  name: ref
  in: path
  description: Ref (branch) of repository.
  required: true
  schema:
    type: string
daOwnerParam:
  name: owner
  in: path
  description: Name of the source owner.
  required: true
  schema:
    type: string
pathParam:
  name: path
  in: path
  description: Path to the source content.
  required: true
  schema:
    type: string
headerParam:
  name: x-da-metadata
  in: header
  schema:
    type: string
    example: '{"aemOrigin":"https://main--blog--adobecom.hlx.page"}'
  description: Value to correlate API requests across systems.