orgParam:
  name: org
  in: path
  description: The organization.
  required: true
  schema:
    type: string
repoParam:
  name: repo
  in: path
  description: Name of the repository.
  required: true
  schema:
    type: string
refParam:
  name: ref
  in: path
  description: Ref (branch) of repository.
  required: true
  schema:
    type: string
pathParam:
  name: path
  in: path
  description: Path to the source content.
  required: true
  schema:
    type: string
guidParam:
  name: guid
  in: path
  description: GUID of the version source.
  required: true
  schema:
    type: string
extReqParam:
  name: ext
  in: path
  description: The source content file extension.
  required: true
  schema:
    type: string
extParam:
  name: ext
  in: path
  description: The source content file extension.
  required: false
  schema:
    type: string
