name: Dark Alley Bot release email

on:
  pull_request_target:
    types:
      - opened
      - closed
      - reopened
    branches:
      - config-api

jobs:
  action:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use email bot
        uses: adobecom/da-email-bot@main
        env:
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: 'release@em9437.da.live'
          FROM_NAME: 'Dark Alley Release'
          SG_KEY: ${{ secrets.SG_KEY }}
          SG_TEMPLATE: 'd-24723d9fc5964674a61426db17553c58'
