name: Build & Test Deploy
on: [push]

env:
  CI_BRANCH: ${{ github.ref_name }}

permissions:
  id-token: write
  contents: write  # semantic-release-dry verifies the write permissions
  issues: read # needed by semantic-release
  pull-requests: write # needed by semantic-release

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/adobe-infra'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm install
      - run: npm test

  test-deploy:
    name: Test Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm install
      - name: extracting last commit message
        run: |
          echo "CI_LAST_COMMIT_MSG=$(git show -s --format="%s")" >> $GITHUB_ENV
          echo CI_LAST_COMMIT_MSG
      - name: Branch Deploy
        id: deploy-worker
        uses: cloudflare/wrangler-action@v3
        with:
          quiet: true
          preCommands: node prepare-deploy.js
          command: deploy -e stage -c wrangler-versioned.toml
          apiToken: ${{ secrets.CLOUDFLARE_AUTH }}
          accountId: ${{secrets.CLOUDFLARE_ACCOUNT}}
      - name: Post-Deployment Integration Test
        run: WORKER_URL="${{ steps.deploy-worker.outputs.deployment-url }}" npm run test:e2e
        env:
          WORKER_URL: ${{ secrets.STAGE_WORKER_URL }}
      - name: Semantic Release (Dry Run)
        run: npm run semantic-release-dry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
